name: build

permissions: read-all

on:
  push:
  pull_request:
  schedule:
  - cron: "7 8 * * 6"  # Run at a random time weekly

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
        imp-branch: [main, develop]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup conda
      run: |
        support/tutorial_tools/setup_ci.sh ${{ matrix.imp-branch }} ${{ matrix.python-version }}
    - name: Test
      run: |
        eval "$(conda shell.bash hook)"
        conda activate python${{ matrix.python-version }}
        pytest support/test/*.py -v
